# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_swig')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_swig')
    _swig = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swig', [dirname(__file__)])
        except ImportError:
            import _swig
            return _swig
        try:
            _mod = imp.load_module('_swig', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _swig = swig_import_helper()
    del swig_import_helper
else:
    import _swig
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _swig.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _swig.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _swig.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _swig.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _swig.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _swig.SwigPyIterator_equal(self, x)

    def copy(self):
        return _swig.SwigPyIterator_copy(self)

    def next(self):
        return _swig.SwigPyIterator_next(self)

    def __next__(self):
        return _swig.SwigPyIterator___next__(self)

    def previous(self):
        return _swig.SwigPyIterator_previous(self)

    def advance(self, n):
        return _swig.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _swig.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _swig.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _swig.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _swig.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _swig.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _swig.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _swig.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _swig.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig.IntVector___nonzero__(self)

    def __bool__(self):
        return _swig.IntVector___bool__(self)

    def __len__(self):
        return _swig.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _swig.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig.IntVector___setitem__(self, *args)

    def pop(self):
        return _swig.IntVector_pop(self)

    def append(self, x):
        return _swig.IntVector_append(self, x)

    def empty(self):
        return _swig.IntVector_empty(self)

    def size(self):
        return _swig.IntVector_size(self)

    def swap(self, v):
        return _swig.IntVector_swap(self, v)

    def begin(self):
        return _swig.IntVector_begin(self)

    def end(self):
        return _swig.IntVector_end(self)

    def rbegin(self):
        return _swig.IntVector_rbegin(self)

    def rend(self):
        return _swig.IntVector_rend(self)

    def clear(self):
        return _swig.IntVector_clear(self)

    def get_allocator(self):
        return _swig.IntVector_get_allocator(self)

    def pop_back(self):
        return _swig.IntVector_pop_back(self)

    def erase(self, *args):
        return _swig.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _swig.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _swig.IntVector_push_back(self, x)

    def front(self):
        return _swig.IntVector_front(self)

    def back(self):
        return _swig.IntVector_back(self)

    def assign(self, n, x):
        return _swig.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _swig.IntVector_resize(self, *args)

    def insert(self, *args):
        return _swig.IntVector_insert(self, *args)

    def reserve(self, n):
        return _swig.IntVector_reserve(self, n)

    def capacity(self):
        return _swig.IntVector_capacity(self)
    __swig_destroy__ = _swig.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _swig.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _swig.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _swig.DoubleVector___bool__(self)

    def __len__(self):
        return _swig.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _swig.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _swig.DoubleVector_pop(self)

    def append(self, x):
        return _swig.DoubleVector_append(self, x)

    def empty(self):
        return _swig.DoubleVector_empty(self)

    def size(self):
        return _swig.DoubleVector_size(self)

    def swap(self, v):
        return _swig.DoubleVector_swap(self, v)

    def begin(self):
        return _swig.DoubleVector_begin(self)

    def end(self):
        return _swig.DoubleVector_end(self)

    def rbegin(self):
        return _swig.DoubleVector_rbegin(self)

    def rend(self):
        return _swig.DoubleVector_rend(self)

    def clear(self):
        return _swig.DoubleVector_clear(self)

    def get_allocator(self):
        return _swig.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _swig.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _swig.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _swig.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _swig.DoubleVector_push_back(self, x)

    def front(self):
        return _swig.DoubleVector_front(self)

    def back(self):
        return _swig.DoubleVector_back(self)

    def assign(self, n, x):
        return _swig.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _swig.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _swig.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _swig.DoubleVector_reserve(self, n)

    def capacity(self):
        return _swig.DoubleVector_capacity(self)
    __swig_destroy__ = _swig.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _swig.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DoubleVectorVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVectorVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVectorVectorVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _swig.DoubleVectorVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig.DoubleVectorVectorVector___nonzero__(self)

    def __bool__(self):
        return _swig.DoubleVectorVectorVector___bool__(self)

    def __len__(self):
        return _swig.DoubleVectorVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _swig.DoubleVectorVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig.DoubleVectorVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig.DoubleVectorVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig.DoubleVectorVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig.DoubleVectorVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig.DoubleVectorVectorVector___setitem__(self, *args)

    def pop(self):
        return _swig.DoubleVectorVectorVector_pop(self)

    def append(self, x):
        return _swig.DoubleVectorVectorVector_append(self, x)

    def empty(self):
        return _swig.DoubleVectorVectorVector_empty(self)

    def size(self):
        return _swig.DoubleVectorVectorVector_size(self)

    def swap(self, v):
        return _swig.DoubleVectorVectorVector_swap(self, v)

    def begin(self):
        return _swig.DoubleVectorVectorVector_begin(self)

    def end(self):
        return _swig.DoubleVectorVectorVector_end(self)

    def rbegin(self):
        return _swig.DoubleVectorVectorVector_rbegin(self)

    def rend(self):
        return _swig.DoubleVectorVectorVector_rend(self)

    def clear(self):
        return _swig.DoubleVectorVectorVector_clear(self)

    def get_allocator(self):
        return _swig.DoubleVectorVectorVector_get_allocator(self)

    def pop_back(self):
        return _swig.DoubleVectorVectorVector_pop_back(self)

    def erase(self, *args):
        return _swig.DoubleVectorVectorVector_erase(self, *args)

    def __init__(self, *args):
        this = _swig.new_DoubleVectorVectorVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _swig.DoubleVectorVectorVector_push_back(self, x)

    def front(self):
        return _swig.DoubleVectorVectorVector_front(self)

    def back(self):
        return _swig.DoubleVectorVectorVector_back(self)

    def assign(self, n, x):
        return _swig.DoubleVectorVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _swig.DoubleVectorVectorVector_resize(self, *args)

    def insert(self, *args):
        return _swig.DoubleVectorVectorVector_insert(self, *args)

    def reserve(self, n):
        return _swig.DoubleVectorVectorVector_reserve(self, n)

    def capacity(self):
        return _swig.DoubleVectorVectorVector_capacity(self)
    __swig_destroy__ = _swig.delete_DoubleVectorVectorVector
    __del__ = lambda self: None
DoubleVectorVectorVector_swigregister = _swig.DoubleVectorVectorVector_swigregister
DoubleVectorVectorVector_swigregister(DoubleVectorVectorVector)

# This file is compatible with both classic and new-style classes.


